package model;
// Generated Nov 18, 2025 10:48:16 AM by Hibernate Tools 4.3.1

import javax.persistence.*;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Table;
import javax.persistence.Id;

@Entity
@Table(name = "tbl_barang")


/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name = "id")
    private Integer id;
    
    @Column(name = "jumlah")
    private String jumlah;
    
    @Column(name = "nama")
    private String nama;

    public Mahasiswa() {
    }

    public Mahasiswa(String jumlah, String nama) {
       this.jumlah = jumlah;
       this.nama = nama;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(String jumlah) {
        this.jumlah = jumlah;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    
    @Override
    public String toString(){
        return "Mahasiswa{" +
                "id=" + id +
                ", nama=" + nama + '\''+
                ", jumlah=" + jumlah + '\''+
                "}";
    }
}


